url: "https://lndh.github.io/breadcrumb-menu-generator" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

page_gen:
- data: 'links'
  template: 'menu'
  name: 'title'
  dir: ''

collection:
  pages:
    output: true
    permalink: ""

defaults:
  -
    scope:
      patch: ""
      type: "pages"
    values:
      layout: "menu"